interface Env {
  DOCUMENTS?: R2Bucket;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  INTERNAL_SERVICE_TOKEN?: string;
  ENCRYPTION_MASTER_KEY?: string;
  PLATFORM_ADMIN_EMAILS?: string;
}
